version: "3.7"
services:
  frontend:
    build: ./frontend
    ports:
      - "3333:3000"
  api:
    build: ./api
    ports:
      - "5555:5000"
  mysql:
    image: mysql
  adminer:
    image: adminer
    ports:
      - "8080:8080"
